// ---------------------------------------------------------------
// ダイアログ
// ---------------------------------------------------------------
#define _DIALOG_SAVE		0
#define _DIALOG_SAVE_DEL	1
#define _DIALOG_LOAD		2
#define _DIALOG_RETURN		3
#define _DIALOG_TITLE		4
#define _DIALOG_SECENE		5
#define _DIALOG_EXIT		6
#define _DIALOG_LOGJUMP		7
#define _DIALOG_QSAVE		8
#define _DIALOG_QLOAD		9
#define _DIALOG_DEFAULT     10

#command $dialog_main( stage, int, object, int ) : int

