//	■グローバルＧ変数　

//▼以下3つは他のGフラグがあるためそちらを使用
//#DEFINE			@GFLAG_FIRST_INITIAL				G[2100]			// Ｇ変数：初回初期化フラグ
//#DEFINE			@GFLAG_GAME_CLEAR					G[2101]			// Ｇ変数：ゲームクリアフラグ
//#DEFINE			@GFLAG_KAISOU						G[2102]			// Ｇ変数：シーン回想中フラグ

#define			@GFLAG_DIALOG_QSAVE					G[2110]			// ダイアログ：クイックセーブ（0の時にチェックON＝確認する）
#define			@GFLAG_DIALOG_QLOAD					G[2111]			// ダイアログ：クイックロード
#define			@GFLAG_DIALOG_SAVE					G[2112]			// ダイアログ：上書きセーブ
#define			@GFLAG_DIALOG_LOAD					G[2113]			// ダイアログ：ロード
#define			@GFLAG_DIALOG_LOGJUMP				G[2114]			// ダイアログ：履歴から再開する
#define			@GFLAG_DIALOG_DELETE				G[2115]			// ダイアログ：セーブデータ削除
#define			@GFLAG_DIALOG_TITLE					G[2116]			// ダイアログ：タイトルに戻る／回想に戻る
#define			@GFLAG_DIALOG_EXIT					G[2117]			// ダイアログ：ゲームを終了する

#define         @GFLAG_DIALOG_DEFAULT               G[2118]         // ダイアログ：設定の初期化（★追加）

#DEFINE			@GFLAG_ANIME_ON_OFF					G[2120]			// アニメのＯＮ／ＯＦＦ
#DEFINE			@GFLAG_CHINKASU_ON_OFF				G[2121]			// チンカス描写のＯＮ／ＯＦＦ
#DEFINE			@GFLAG_SHASEI_COUNT_ON_OFF			G[2122]			// 射精カウントのＯＮ／ＯＦＦ
#DEFINE			@GFLAG_DASHI_ON_OFF					G[2123]			// 中出し／外出しの設定

#DEFINE			@GFLAG_CONFIG_PAGE					G[2130]			// 前回のCONFIGのページを覚えておく
#DEFINE			@GFLAG_EXTRA_MODE					G[2133]			// EXTRAのページを記憶
#DEFINE			@GFLAG_EXTRA_CGMODE_PAGE			G[2134]			// EXTRAのページを記憶／CGモード
#DEFINE			@GFLAG_EXTRA_SCENE_PAGE				G[2135]			// EXTRAのページを記憶／SCENE
#DEFINE			@GFLAG_EXTRA_MUSIC_PAGE				G[2136]			// EXTRAのページを記憶／MUSIC

