


//-----------------------------------------------
//320_キッチンまわり・食事

#MACRO	@pcm_dish_wash(@pcmch(0))	$pcmplay(320,2,@pcmch)
#MACRO	@pcm_dish_wash_distance(@pcmch(0))	$pcmplay(321,2,@pcmch)
#MACRO	@pcm_pour_hotwater(@pcmch(0))	$pcmplay(322,0,@pcmch)
#MACRO	@pcm_pile_dish(@pcmch(0))	$pcmplay(323,0,@pcmch)
#MACRO	@pcm_pile_dish2(@pcmch(0))	$pcmplay(324,0,@pcmch)
#MACRO	@pcm_kichen_conro(@pcmch(0))	$pcmplay(325,2,@pcmch)
#MACRO	@pcm_sink_door(@pcmch(0))	$pcmplay(326,2,@pcmch)
#MACRO	@pcm_dish_spoon(@pcmch(0))	$pcmplay(327,0,@pcmch)
#MACRO	@pcm_dish_spoon_drop(@pcmch(0))	$pcmplay(328,0,@pcmch)
#MACRO	@pcm_table_cup(@pcmch(0))	$pcmplay(329,0,@pcmch)
#MACRO	@pcm_kichen_niru(@pcmch(0))	$pcmplay(330,3,@pcmch)
#MACRO	@pcm_kichen_nabe(@pcmch(0))	$pcmplay(331,0,@pcmch)
#MACRO	@pcm_kichen_kiru(@pcmch(0))	$pcmplay(332,3,@pcmch)
#MACRO	@pcm_kichen_wrap(@pcmch(0))	$pcmplay(333,0,@pcmch)
#MACRO	@pcm_curry_box_open(@pcmch(0))	$pcmplay(334,0,@pcmch)
#MACRO	@pcm_kichen_toaster(@pcmch(0))	$pcmplay(335,2,@pcmch)
#MACRO	@pcm_pile_dish3(@pcmch(0))	$pcmplay(336,2,@pcmch)
#MACRO	@pcm_meal_start(@pcmch(0))	$pcmplay(337,0,@pcmch)
#MACRO	@pcm_rice_cooker(@pcmch(0))	$pcmplay(338,2,@pcmch)
#MACRO	@pcm_microwave(@pcmch(0))	$pcmplay(339,2,@pcmch)
#MACRO	@pcm_microwave_door(@pcmch(0))	$pcmplay(340,2,@pcmch)
#MACRO	@pcm_burn_eggs(@pcmch(0))	$pcmplay(341,3,@pcmch)
#MACRO	@pcm_refrigerator(@pcmch(0))	$pcmplay(342,2,@pcmch)


//-----------------------------------------------
//350_シャワー・水音

#MACRO	@pcm_shower_stop(@pcmch(0))	$pcmplay(350,0,@pcmch)
#MACRO	@pcm_shower_take(@pcmch(0))	$pcmplay(351,3,@pcmch)
#MACRO	@pcm_shower_stop_after1(@pcmch(0))	$pcmplay(352,2,@pcmch)
#MACRO	@pcm_shower_stop_after2(@pcmch(0))	$pcmplay(353,2,@pcmch)
#MACRO	@pcm_shower_take_distance(@pcmch(0))	$pcmplay(354,3,@pcmch)
#MACRO	@pcm_dryer(@pcmch(0))	$pcmplay(355,3,@pcmch)
#MACRO	@pcm_drain_water(@pcmch(0))	$pcmplay(356,2,@pcmch)
#MACRO	@pcm_washer(@pcmch(0))	$pcmplay(357,3,@pcmch)
#MACRO	@pcm_washroom(@pcmch(0))	$pcmplay(358,3,@pcmch)
#MACRO	@pcm_bash_take(@pcmch(0))	$pcmplay(359,2,@pcmch)
#MACRO	@pcm_bash_faucet(@pcmch(0))	$pcmplay(360,0,@pcmch)
#MACRO	@pcm_bash_foam(@pcmch(0))	$pcmplay(361,0,@pcmch)

//-----------------------------------------------
//370_ドア・ふすま・ノック

#MACRO	@pcm_door_glass_open(@pcmch(0))	$pcmplay(370,2,@pcmch)
#MACRO	@pcm_door_glass_close(@pcmch(0))	$pcmplay(371,2,@pcmch)
#MACRO	@pcm_door_nock(@pcmch(0))	$pcmplay(372,0,@pcmch)
#MACRO	@pcm_door_knob(@pcmch(0))	$pcmplay(373,0,@pcmch)
#MACRO	@pcm_door_open(@pcmch(0))	$pcmplay(374,0,@pcmch)
#MACRO	@pcm_door_close(@pcmch(0))	$pcmplay(375,0,@pcmch)
#MACRO	@pcm_door_hotel_open(@pcmch(0))	$pcmplay(376,0,@pcmch)
#MACRO	@pcm_door_hotel_close(@pcmch(0))	$pcmplay(377,0,@pcmch)
// #MACRO	@pcm_fusuma_nock(@pcmch(0))	$pcmplay(378,2,@pcmch)
// #MACRO	@pcm_fusuma_open(@pcmch(0))	$pcmplay(379,0,@pcmch)
// #MACRO	@pcm_fusuma_close(@pcmch(0))	$pcmplay(380,0,@pcmch)
#MACRO	@pcm_door_school_open(@pcmch(0))	$pcmplay(381,0,@pcmch)
#MACRO	@pcm_door_school_close(@pcmch(0))	$pcmplay(382,0,@pcmch)
#MACRO	@pcm_door_school_nock(@pcmch(0))	$pcmplay(383,0,@pcmch)
#MACRO	@pcm_door_entrance_distance(@pcmch(0))	$pcmplay(384,3,@pcmch)
#MACRO	@pcm_door_entrance_open(@pcmch(0))	$pcmplay(385,0,@pcmch)
#MACRO	@pcm_door_entrance_close(@pcmch(0))	$pcmplay(386,0,@pcmch)
#MACRO	@pcm_door_iron(@pcmch(0))	$pcmplay(387,3,@pcmch)
#MACRO	@pcm_door_bath(@pcmch(0))	$pcmplay(388,3,@pcmch)


//-----------------------------------------------
//410_鍵

 #MACRO	@pcm_key_autolock(@pcmch(0))	$pcmplay(410,2,@pcmch)
 #MACRO	@pcm_key_door(@pcmch(0))	$pcmplay(411,0,@pcmch)
// #MACRO	@pcm_key_fusuma(@pcmch(0))	$pcmplay(412,0,@pcmch)
// #MACRO	@pcm_key_put(@pcmch(0))	$pcmplay(413,0,@pcmch)
 #MACRO	@pcm_key_entrance_unlock(@pcmch(0))	$pcmplay(414,0,@pcmch)
 #MACRO	@pcm_key_entrance_lock(@pcmch(0))	$pcmplay(415,0,@pcmch)
 #MACRO	@pcm_key_entrance_enter(@pcmch(0))	$pcmplay(416,0,@pcmch)
 #MACRO	@pcm_key_entrance_distance(@pcmch(0))	$pcmplay(417,3,@pcmch)
// #MACRO	@pcm_key_window(@pcmch(0))	$pcmplay(418,0,@pcmch)
// #MACRO	@pcm_key_barrel(@pcmch(0))	$pcmplay(419,3,@pcmch)




//-----------------------------------------------
//490_足音・コンクリ・床・草むら

#MACRO	@pcm_walk_road(@pcmch(0))	$pcmplay(490,3,@pcmch)
#MACRO	@pcm_dash_conc_away(@pcmch(0))	$pcmplay(491,3,@pcmch)
#MACRO	@pcm_walk_conc(@pcmch(0))	$pcmplay(492,3,@pcmch)
// #MACRO	@pcm_dash_tatami_away(@pcmch(0))	$pcmplay(493,3,@pcmch)
// #MACRO	@pcm_walk_tatami(@pcmch(0))	$pcmplay(494,3,@pcmch)
// #MACRO	@pcm_walk_tatami_come(@pcmch(0))	$pcmplay(495,3,@pcmch)
// #MACRO	@pcm_walk_tatami_stop(@pcmch(0))	$pcmplay(496,3,@pcmch)
// #MACRO	@pcm_walk_snow_fast(@pcmch(0))	$pcmplay(497,3,@pcmch)
// #MACRO	@pcm_walk_snow_come(@pcmch(0))	$pcmplay(498,3,@pcmch)
// #MACRO	@pcm_dash_snow(@pcmch(0))	$pcmplay(499,3,@pcmch)
// #MACRO	@pcm_dash_snow_away(@pcmch(0))	$pcmplay(500,3,@pcmch)
// #MACRO	@pcm_walk_snow_2persons(@pcmch(0))	$pcmplay(501,3,@pcmch)
// #MACRO	@pcm_walk_snow(@pcmch(0))	$pcmplay(502,3,@pcmch)
// #MACRO	@pcm_walk_snow_stop(@pcmch(0))	$pcmplay(503,3,@pcmch)
#MACRO	@pcm_walk_grass(@pcmch(0))	$pcmplay(504,3,@pcmch)
#MACRO	@pcm_walk_iron_stairs_down(@pcmch(0))	$pcmplay(505,3,@pcmch)
#MACRO	@pcm_walk_iron_stairs_up(@pcmch(0))	$pcmplay(506,3,@pcmch)
#MACRO	@pcm_walk_stop(@pcmch(0))	$pcmplay(507,3,@pcmch)

// #MACRO	@pcm_walk_rain(@pcmch(0))	$pcmplay(508,4,@pcmch)
// #MACRO	@pcm_dash_rain(@pcmch(0))	$pcmplay(509,4,@pcmch)
// #MACRO	@pcm_walk_stop_rain(@pcmch(0))	$pcmplay(510,0,@pcmch)
#MACRO	@pcm_walk_yuka(@pcmch(0))	$pcmplay(511,4,@pcmch)
#MACRO	@pcm_walk_yuka_come(@pcmch(0))	$pcmplay(512,4,@pcmch)
#MACRO	@pcm_walk_yuka_away(@pcmch(0))	$pcmplay(513,4,@pcmch)
#MACRO	@pcm_dash_yuka(@pcmch(0))	$pcmplay(514,4,@pcmch)
#MACRO	@pcm_dash_yuka_come(@pcmch(0))	$pcmplay(515,4,@pcmch)
#MACRO	@pcm_dash_yuka_away(@pcmch(0))	$pcmplay(516,4,@pcmch)



//-----------------------------------------------
//520_布や紙・広げる・破く

#MACRO	@pcm_memo(@pcmch(0))	$pcmplay(520,3,@pcmch)
#MACRO	@pcm_paper_magic_maru(@pcmch(0))	$pcmplay(521,2,@pcmch)
#MACRO	@pcm_paper_magic_batu(@pcmch(0))	$pcmplay(522,2,@pcmch)
#MACRO	@pcm_paper_magic_kaku(@pcmch(0))	$pcmplay(523,3,@pcmch)
#MACRO	@pcm_paper_pencil_kaku(@pcmch(0))	$pcmplay(524,3,@pcmch)
#MACRO	@pcm_paper_gosogoso(@pcmch(0))	$pcmplay(525,2,@pcmch)
#MACRO	@pcm_paper_page(@pcmch(0))	$pcmplay(526,0,@pcmch)
#MACRO	@pcm_paper_open(@pcmch(0))	$pcmplay(527,0,@pcmch)
#MACRO	@pcm_paper_shake(@pcmch(0))	$pcmplay(528,0,@pcmch)
#MACRO	@pcm_paperbag_open(@pcmch(0))	$pcmplay(529,2,@pcmch)
#MACRO	@pcm_cloth_takeoff_coat(@pcmch(0))	$pcmplay(530,2,@pcmch)
#MACRO	@pcm_cloth_rub(@pcmch(0))	$pcmplay(531,2,@pcmch)
#MACRO	@pcm_cloth_basabasa(@pcmch(0))	$pcmplay(532,2,@pcmch)
#MACRO	@pcm_cloth_mekuru(@pcmch(0))	$pcmplay(533,2,@pcmch)
#MACRO	@pcm_cloth_takeout(@pcmch(0))	$pcmplay(534,2,@pcmch)
#MACRO	@pcm_cloth_break(@pcmch(0))	$pcmplay(535,2,@pcmch)


//-----------------------------------------------
//540_物を置く・叩く

#MACRO	@pcm_kisimu_door(@pcmch(0))	$pcmplay(540,2,@pcmch)
#MACRO	@pcm_kisimu_light(@pcmch(0))	$pcmplay(541,2,@pcmch)
#MACRO	@pcm_kisimu_heavy(@pcmch(0))	$pcmplay(542,2,@pcmch)
#MACRO	@pcm_put_table_pencil(@pcmch(0))	$pcmplay(543,0,@pcmch)
#MACRO	@pcm_strike_table(@pcmch(0))	$pcmplay(544,0,@pcmch)
#MACRO	@pcm_put_bag(@pcmch(0))	$pcmplay(545,0,@pcmch)
#MACRO	@pcm_strike_bed(@pcmch(0))	$pcmplay(546,0,@pcmch)
#MACRO	@pcm_strike_desk(@pcmch(0))	$pcmplay(547,0,@pcmch)
#MACRO	@pcm_put_light_metal(@pcmch(0))	$pcmplay(548,0,@pcmch)
#MACRO	@pcm_put_hard(@pcmch(0))	$pcmplay(549,0,@pcmch)
#MACRO	@pcm_put_heavy(@pcmch(0))	$pcmplay(550,0,@pcmch)
#MACRO	@pcm_put_tatami(@pcmch(0))	$pcmplay(551,0,@pcmch)
#MACRO	@pcm_strike_tatami_strong(@pcmch(0))	$pcmplay(552,0,@pcmch)
#MACRO	@pcm_strike_tatami(@pcmch(0))	$pcmplay(553,0,@pcmch)
#MACRO	@pcm_put_wood_light(@pcmch(0))	$pcmplay(554,0,@pcmch)
#MACRO	@pcm_put_wood_heavy(@pcmch(0))	$pcmplay(555,0,@pcmch)
#MACRO	@pcm_coin_drop(@pcmch(0))	$pcmplay(556,2,@pcmch)
#MACRO	@pcm_chair_sit(@pcmch(0))	$pcmplay(557,2,@pcmch)
#MACRO	@pcm_chair_standup(@pcmch(0))	$pcmplay(558,2,@pcmch)



//-----------------------------------------------
//560_その他日常生活(中)

#MACRO	@pcm_switch_aircon(@pcmch(0))	$pcmplay(560,3,@pcmch)
#MACRO	@pcm_curtain_open(@pcmch(0))	$pcmplay(561,0,@pcmch)
#MACRO	@pcm_curtain_close(@pcmch(0))	$pcmplay(562,0,@pcmch)
// #MACRO	@pcm_trashbag_throw(@pcmch(0))	$pcmplay(563,0,@pcmch)
// #MACRO	@pcm_trashbag_close(@pcmch(0))	$pcmplay(564,0,@pcmch)
// #MACRO	@pcm_switch_stove(@pcmch(0))	$pcmplay(565,3,@pcmch)
// #MACRO	@pcm_hataki(@pcmch(0))	$pcmplay(566,2,@pcmch)
 #MACRO	@pcm_switch_lamp_off(@pcmch(0))	$pcmplay(568,0,@pcmch)
 #MACRO	@pcm_switch_lamp_on(@pcmch(0))	$pcmplay(569,0,@pcmch)
// #MACRO	@pcm_tatami_sit(@pcmch(0))	$pcmplay(570,0,@pcmch)
// #MACRO	@pcm_tatami_standup(@pcmch(0))	$pcmplay(571,0,@pcmch)
// #MACRO	@pcm_tatami_broom(@pcmch(0))	$pcmplay(572,2,@pcmch)
//#MACRO	@pcm_window_open(@pcmch(0))	$pcmplay(573,2,@pcmch)
//#MACRO	@pcm_window_close(@pcmch(0))	$pcmplay(574,2,@pcmch)
#MACRO	@pcm_switch_wall_off(@pcmch(0))	$pcmplay(575,0,@pcmch)
#MACRO	@pcm_switch_wall_on(@pcmch(0))	$pcmplay(576,0,@pcmch)
// #MACRO	@pcm_wash_brush1(@pcmch(0))	$pcmplay(577,3,@pcmch)
// #MACRO	@pcm_wash_brush2(@pcmch(0))	$pcmplay(578,3,@pcmch)
// #MACRO	@pcm_wash_yuka_kosuru(@pcmch(0))	$pcmplay(579,3,@pcmch)
// #MACRO	@pcm_cleaner(@pcmch(0))	$pcmplay(580,3,@pcmch)
#MACRO	@pcm_lunchbreak_gaya(@pcmch(0))	$pcmplay(581,3,@pcmch)

// #MACRO	@pcm_glass_break(@pcmch(0))	$pcmplay(582,3,@pcmch)
// #MACRO	@pcm_glass_break_cleaner(@pcmch(0))	$pcmplay(583,3,@pcmch)
#MACRO	@pcm_keyboard(@pcmch(0))	$pcmplay(584,4,@pcmch)
#MACRO	@pcm_keyboard_once(@pcmch(0))	$pcmplay(585,3,@pcmch)
#MACRO	@pcm_keyboard_speed(@pcmch(0))	$pcmplay(586,4,@pcmch)
// #MACRO	@pcm_timecard(@pcmch(0))	$pcmplay(587,3,@pcmch)


//-----------------------------------------------
//590_その他日常生活(屋外)

#MACRO	@pcm_elevator_stop(@pcmch(0))	$pcmplay(590,0,@pcmch)
//#MACRO	@pcm_caster(@pcmch(0))	$pcmplay(591,3,@pcmch)
// #MACRO	@pcm_tabako(@pcmch(0))	$pcmplay(592,3,@pcmch)
// #MACRO	@pcm_akikan(@pcmch(0))	$pcmplay(593,0,@pcmch)
//#MACRO	@pcm_jihanki_buy(@pcmch(0))	$pcmplay(594,3,@pcmch)
//#MACRO	@pcm_jihanki_pay(@pcmch(0))	$pcmplay(595,0,@pcmch)
// #MACRO	@pcm_car_engine(@pcmch(0))	$pcmplay(596,3,@pcmch)
// #MACRO	@pcm_car_door_close(@pcmch(0))	$pcmplay(597,3,@pcmch)
// #MACRO	@pcm_car_stop(@pcmch(0))	$pcmplay(598,3,@pcmch)
// #MACRO	@pcm_car_start(@pcmch(0))	$pcmplay(599,3,@pcmch)
// #MACRO	@pcm_ambulance(@pcmch(0))	$pcmplay(600,3,@pcmch)
// #MACRO	@pcm_ambulance_sumaho(@pcmch(0))	$pcmplay(601,3,@pcmch)
// #MACRO	@pcm_shrine_bell(@pcmch(0))	$pcmplay(602,0,@pcmch)
// #MACRO	@pcm_shrine_2applause(@pcmch(0))	$pcmplay(603,0,@pcmch)

// #MACRO	@pcm_rain_car(@pcmch(0))	$pcmplay(604,5,@pcmch)
#MACRO	@pcm_wedding_bell(@pcmch(0))	$pcmplay(605,5,@pcmch)
// #MACRO	@pcm_cafe_in(@pcmch(0))	$pcmplay(606,2,@pcmch)
// #MACRO	@pcm_cafe_ice(@pcmch(0))	$pcmplay(607,2,@pcmch)
// #MACRO	@pcm_train_stop(@pcmch(0))	$pcmplay(608,2,@pcmch)
// #MACRO	@pcm_train_door_open(@pcmch(0))	$pcmplay(609,2,@pcmch)
// #MACRO	@pcm_train_door_close(@pcmch(0))	$pcmplay(610,2,@pcmch)
#MACRO	@pcm_train_start(@pcmch(0))	$pcmplay(611,5,@pcmch)
// #MACRO	@pcm_train_move(@pcmch(1))	$pcmplay(612,5,@pcmch) //1
// #MACRO	@pcm_train_in_mans(@pcmch(0))	$pcmplay(613,2,@pcmch)
// #MACRO	@pcm_train_announcement(@pcmch(0))	$pcmplay(614,3,@pcmch)
// #MACRO	@pcm_hato(@pcmch(0))	$pcmplay(615,3,@pcmch)
// #MACRO	@pcm_hanabi1(@pcmch(0))	$pcmplay(616,5,@pcmch)
// #MACRO	@pcm_hanabi2(@pcmch(0))	$pcmplay(617,5,@pcmch)
// #MACRO	@pcm_hanabi3(@pcmch(0))	$pcmplay(618,5,@pcmch)

