

#DEFINE @射精管理（そくばく） @ruby(そくばく) 射精管理 @ruby

#DEFINE @箕々崎（みがさき） @ruby(みがさき) 箕々崎 @ruby

#DEFINE @何時（なんどき） @ruby(なんどき) 何時 @ruby

#DEFINE @珠理奈（じゅりな） @ruby(じゅりな) 珠理奈 @ruby
#DEFINE @蒼汰（そうた） @ruby(そうた) 蒼汰 @ruby
#DEFINE @古宮（こみや） @ruby(こみや) 古宮 @ruby
#DEFINE @矢切（やぎり） @ruby(やぎり) 矢切 @ruby
#DEFINE @香住（かすみ） @ruby(かすみ) 香住 @ruby

#DEFINE @邪（よこしま） @ruby(よこしま) 邪 @ruby
#DEFINE @糺（ただ） @ruby(ただ) 糺 @ruby
#DEFINE @誘（いざな） @ruby(いざな) 誘 @ruby
#DEFINE @件（くだん） @ruby(くだん) 件 @ruby

#DEFINE ｛  color(250) print("【")
#DEFINE ｝  print("】") color
