// 環境情報用変数
global.ENV_Maker     = "あっぷりけ";
global.ENV_MakerURL  = "http://www.applique-soft.com/";
global.ENV_GameName  = "黄昏の先にのぼる明日-あっぷりけFanDisc-";
global.ENV_GameURL   = "http://www.applique-soft.com/apfd/top.html";
global.ENV_GameId    = "{035FDFB7-FF67-493D-9FF2-B90DA364D94E}";
global.ENV_ReadmeFile= "readme.txt";
global.ENV_ReadmeName= "お読みください";
global.ENV_IconFile  = "setup/icon.ico";
global.ENV_PKeyName  = "";
// ※このファイルは直接編集しないでください
// （元となる MakeConfig.txt を編集して MakeMenuから直makeの「gameconfig」で更新）
