/**
 * スタッフロール描画用の定義ファイル
 */
%[
	// 表示タイプ（0:ソフトレンダ，1:プリレンダ画像/ファイルが無い場合はソフトレンダ）
type      : 1,

	// ロールテキストスクリプト
file      : "staffroll.txt",

	// プリレンダ画像のベース名（省略時 file )
base      : "rollimage_",

	// ソフトレンダ時のフォントフェイス
font      : global.SystemDefaultFontFace, //"ＭＳ Ｐゴシック",

	// 色
color     : 0xffffff,

	// フチ取り
edgesize  : 2,
edgecolor : 0x000000,
emphasis  : 2048,

	// 段階別サイズ
normal    : 24,
small     : 16,
medium    : 20,
big       : 36,

	// 右寄せ・左寄せした時の左右余白
indent    : 80,

	// 行間定義（linewidth: 現在行の縦幅の指定倍数を次の行とする， linespace:行間を固定サイズ空ける）
linewidth : 2.0,
linespace : 0,

	]