/*
検索パスの追加登録方法：
 setupSubFolders([ サブフォルダ名, ... ]);
  サブフォルダ名：data/以下のフォルダ名。サブサブフォルダ以下は"/"で区切る
 */

setupSubFolders([
	/* 記述例：
	"scenario/part1"
	"scenario/part2"

	"fgimage/chara1",
	"fgimage/chara2",

	"image/cutin",
	"image/effect/type1",
	"image/effect/type2",

	"voice/chara1",
	"voice/chara2",
	 ここまでコメント */

	"bgimage/large",
	"bgimage/ms",
	"bgimage/cn",
	"bgimage/sin",
//	"bgimage/ms/large",
	"bgimage/cn/large",
	"bgimage/sin/large",

	"bgm/ms",
	"bgm/cn",
	"bgm/sin",

	"sound/cn",
	"sound/ms",
	"sound/sin",
	"sound/sysse",

	"scenario/あっぷりけ放送局",
	"scenario/コンチェルトストレイジ",
	"scenario/コンチェルトストレイジ/aルート（一度敗北）",
	"scenario/コンチェルトストレイジ/bルート（二度敗北）",
	"scenario/フラグメント",
	"scenario/黄昏のシンセミア Another",
	"scenario/見上げた空におちていく Wish After",
	"scenario/麻雀チュートリアル",

	"fgimage/akane",
	"fgimage/iroha",
	"fgimage/sachiko",
	"fgimage/ginko",
	"fgimage/shouko",
	"fgimage/satsuki",
	"fgimage/sakuya",
	"fgimage/misato",
	// １年後
	"fgimage/shouaf",
	"fgimage/sachiaf",

	"fgimage/001_クシミタマ",
	"fgimage/002_春奈",
	"fgimage/003_椋木悠斗",
	"fgimage/004_ユキ",
	"fgimage/005_アル",
	"fgimage/006_羽二生真央",
	"fgimage/007_清川心音",
	"fgimage/008_式澤一真",
	"fgimage/009_笹原真菜美",
	"fgimage/010_椋木優子",
	"fgimage/011_加藤鈴",
	"fgimage/012_速見礼次",
	"fgimage/013_倉上進矢",
	"fgimage/014_神凪莉都",
	"fgimage/015_今里和奏",
	"fgimage/016_名凪星華",
	"fgimage/017_東条白雪",
	"fgimage/018_夕月小夜璃",
	"fgimage/019_タマ",
	"fgimage/020_寺内陽太",
	"fgimage/021_上杉慶一",
	"fgimage/022_椎堂小太郎",
	"fgimage/023_クラウス＝シュルツ＝長嶺",
	"fgimage/024_南条麻里香",
	"fgimage/025_斎宮媛子",
	"fgimage/026_天野深弥",
	"fgimage/027_神無月朱美",
	"fgimage/028_皆神孝介",

	"image/mah-jang",
	"image/mah-jang/牌",
	"image/mah-jang/牌/large",
	"image/mah-jang/牌/small",
	"image/mah-jang/牌/右席の牌向き",
	"image/mah-jang/牌/左席の牌向き",
	"image/mah-jang/牌/対面の牌向き",
	"image/mah-jang/キャプション",
	"image/mah-jang/キャプション/cap_large",

	"image/prologue",
	"image/birthday",
	"image/radio",
	"image/staff",
	"image/flow",

	"main/staffroll",

	"evimage/cn",
	"evimage/sin",
	"evimage/large",

	"voice",
	"voice/_誕生日",
	"voice/いろは",
	"voice/おじさん",
	"voice/クラウス",
	"voice/さくや",
	"voice/タマ",
	"voice/奇御魂",
	"voice/銀子",
	"voice/犬",
	"voice/沙智子",
	"voice/皐月",
	"voice/式澤",
	"voice/朱音",
	"voice/朱美",
	"voice/春菜",
	"voice/女子生徒",
	"voice/小太郎",
	"voice/小夜璃",
	"voice/上杉",
	"voice/心音",
	"voice/深弥",
	"voice/真央",
	"voice/真菜美",
	"voice/星華",
	"voice/白雪",
	"voice/美里",
	"voice/媛子",
	"voice/麻理香",
	"voice/優子",
	"voice/陽太",
	"voice/礼次",
	"voice/鈴",
	"voice/莉都",
	"voice/翔子",
	"voice/和奏",
	"voice/ユキ",
	"voice/アル",


	]);


