from gen_transdict_LIB import *

a = transdict()

#a.addname(jp_name=[],chs_name=[],sex="",role="",other="",reverse=False)

a.addname(jp_name=["桜井　真実"],chs_name=["樱井　真实"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["皆月　明海"],chs_name=["皆月　明海"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["芹沢　小夜子"],chs_name=["芹沢　小夜子"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["藍田　菜摘"],chs_name=["蓝田　菜摘"],sex="woman",role="teacher",other="",reverse=False)
a.addname(jp_name=["野島　まゆ子"],chs_name=["野岛　真由子"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["羽根田　玖美子"],chs_name=["羽根田　玖美子"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["丹羽　望夫"],chs_name=["丹羽　望夫"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["治見"],chs_name=["治见"],sex="teacher",role="",other="",reverse=False)
a.addname(jp_name=["二階堂"],chs_name=["二阶堂"],sex="man",role="teacher",other="",reverse=False)
a.addname(jp_name=["スダ"],chs_name=["苏达"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["イズミ"],chs_name=["泉"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["根津"],chs_name=["根津"],sex="man",role="teacher",other="",reverse=False)
a.addname(jp_name=["東野　百合恵"],chs_name=["东野　百合恵"],sex="woman",role="teacher",other="",reverse=False)
a.addname(jp_name=["片山　昌俊"],chs_name=["片山　昌俊"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["田口　義和"],chs_name=["田口　义和"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["福崎　育巳"],chs_name=["福崎　育巳"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["矢崎　良"],chs_name=["矢崎　良"],sex="",role="",other="",reverse=False)
a.addname(jp_name=["渡辺"],chs_name=["渡边"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["森　守男"],chs_name=["森　守男"],sex="man",role="",other="",reverse=False)
a.addname(jp_name=["藤原　篤子"],chs_name=["藤原　笃子"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["石川　香津実"],chs_name=["石川　香津实"],sex="girl",role="",other="",reverse=False)
a.addname(jp_name=["チミチミ"],chs_name=["奇米奇米"],sex="man",role="nick name of 治見",other="teacher",reverse=False)
a.addname(jp_name=["まぼちゃん"],chs_name=["麻波酱"],sex="",role="",other="",reverse=False)
a.addname(jp_name=["まぼ"],chs_name=["麻波"],sex="",role="",other="",reverse=False)
a.addname(jp_name=["保科　纯"],chs_name=["保科　纯"],sex="man",role="",other="",reverse=False)

a.gen_dict()
a.savetxt("月光.txt")
#a.savejson("月光.json")