[GLOBAL]
DEBUG=0
MODE=3
#1:CREATEFONTA 2:CREATEFONTINDERECTA
LOADDLL=FONTCHANGER.dll
LE=1
TIMER=0
[FONT]
PRINTINFO=1
ConditCHANGEFONT=0
CHANGEFONT=1
CHANGECHARSET=0
FONTNAME=Simsun
FONTFILENAME=
HeightScaleFactor=100
WidthScaleFactor=100
cWeight=600
rotate=0
[STARTMESSAGE]
MODELTYPE=deepseek