from gen_transdict_LIB import *

a = transdict()

#a.addname(jp_name=[],chs_name=[],sex="",role="",other="",reverse=False)

a.addname(jp_name=["トシロー カシマ"],chs_name=["杜志郎 鹿岛"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["シェリル マクレガー"],chs_name=["谢丽尔 麦格雷戈"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["アンヌ ポートマン"],chs_name=["安妮 波特曼"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["ニナ オルロック"],chs_name=["妮娜 奥尔洛克"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["アリヤ タカジョウ"],chs_name=["鹰匠 亚莉矢"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["アイザック フォレスト"],chs_name=["艾萨克 福雷斯特"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["ルーシー ミルドレッド"],chs_name=["露西 米尔德丽德"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["ジョージ ゴードン バイロン"],chs_name=["乔治 戈登 拜伦"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["ケイトリン ワインハウス"],chs_name=["凯特琳 温豪斯"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["美影"],chs_name=["美影"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["カーマイン"],chs_name=["卡蜜茵"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["マジェンタ"],chs_name=["玛珍塔"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["スカーレット"],chs_name=["斯卡蕾特"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["モーガン クインシー"],chs_name=["摩根 昆西"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["エルンスト ゴドフリ"],chs_name=["恩斯特 戈德弗里"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["ヴァネッサ クラリモンド"],chs_name=["凡妮莎 克拉里蒙德"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["ヴァン エレコーゼ"],chs_name=["范 埃雷科泽"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["ウイリアム ギャラハッド"],chs_name=["威廉 加拉哈德"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["アルフライラ ワ ライラ"],chs_name=["阿尔芙莱拉 瓦 莱拉"],sex="woman",role="",other="",reverse=True)
a.addname(jp_name=["ヴィクトル シュヴァンクマイエル クラウス"],chs_name=["维克托 施万克迈尔 克劳斯"],sex="man",role="",other="",reverse=True)
a.addword(jp="ホワイト・パイル",chs="白之派尔",other="")
a.addword(jp="コミュニティ",chs="共同体",other="")
a.addword(jp="鎖輪",chs="锁轮",other="")
a.addword(jp="縛血者",chs="缚血者",other="")
a.addword(jp="カサノヴァ",chs="卡萨诺瓦",other="")
a.addword(jp="リリス",chs="莉莉丝",other="")
a.addword(jp="柩の娘",chs="棺之少女",other="")
a.addword(jp="藍血貴",chs="蓝血贵族",other="")

a.gen_dict()
a.savetxt("项目GPT字典.txt")