/*
#replace	@レコード_テスト００１			000
#replace	@レコード_テスト００２			001
#replace	@レコード_テスト００３			002
#replace	@レコード_テスト００４			003
#replace	@レコード_テスト００５			004
#replace	@レコード_テスト００６			005
#replace	@レコード_テスト００７			006
#replace	@レコード_テスト００８			007
#replace	@レコード_テスト００９			008
#replace	@レコード_テスト０１０			009
#replace	@レコード_テスト０１１			010
#replace	@レコード_テスト０１２			011
#replace	@レコード_テスト０１３			012
#replace	@レコード_テスト０１４			013
#replace	@レコード_テスト０１５			014
#replace	@レコード_テスト０１６			015
#replace	@レコード_テスト０１７			016
#replace	@レコード_テスト０１８			017
#replace	@レコード_テスト０１９			018
#replace	@レコード_テスト０２０			019
#replace	@レコード_テスト０２１			020
#replace	@レコード_テスト０２２			021
#replace	@レコード_テスト０２３			022
#replace	@レコード_テスト０２４			023
#replace	@レコード_テスト０２５			024
*/
#replace	@レコード最大数					050
