//===========================================================================
//!
//!    @file     language.inc
//!    @brief    言語定義
//!
//!    @author   Copyright (C)2023- VISUAL ARTS. All rights reserved.
//!    @author   Kazuya Takahashi
//!    @note     none
//!
//===========================================================================

#define		@check_lang			$lang_jp

#define		$lang_jp			0	//日本語
#define		$lang_en			1	//英語
#define		$lang_ch			2	//?体中文
#define		$lang_de			3	//ドイツ語
#define		$lang_es			4	//スペイン語
#define		$lang_zhtw			5	//繁体中文
