[GLOBAL]
#MODE1为文本提取（不推荐，建议解包提取），MODE2为译文注入。
MODE=2
#为1时启用win10兼容性补丁，需要将win10_patch.dll放入补丁中
WIN10PATCH=1
#调试用
DEBUG=0
[FONT]
FONTNAME=Simsun
[LOADER]
#TARGET输入游戏主程序名
TARGET=TESTAMENT.EXE
DLL=SBRioshiina.dll
[STARTMESSAGE]
MODELTYPE=Claude-3.5-sonnet