; malie.ini
; MalieSystem 設定

[SYSTEM]

; システム情報
COMPANY=Greenwood
BRAND=light
TITLE=Vermilion
VERSION=1.0
ICON=
PRODUCT=VER

; フォントサイズ
FontSize=25
;FontSize=37
TextColor=#FFFFFF
WindowColor=#e6145a
FPS=30
GDICursor=TRUE
Mpeg1VideoDecoder=

; 
ScreenWidth=1024
ScreenHeight=600


[CURSOR]
ARROW=.\system\arrow.cur

[CONFIG]

; 名前
NAME01=
NAME02=

; 音声
CHARA01=tos,
CHARA02=she,
CHARA03=ann,
CHARA04=nin,
CHARA05=ari,
CHARA06=kei,
CHARA07=rus,
CHARA08=alf,
CHARA09=mik,
CHARA10=car,
CHARA11=mag,
CHARA12=sca,
CHARA13=cla,
CHARA14=mor,
CHARA15=aiz,
CHARA16=bir,
CHARA17=god,
CHARA18=kra,
CHARA19=van,
CHARA20=wil,
CHARA21=hak,
CHARA22=others,

; サウンドテスト
VoiceTest=v_she0006
SeTest=1
SystemSeTest=1
EnvTest=36

[SYSTEMBGM]
TITLE=02
CGMODE=
SCENEMODE=
ANOTHERSTORY=

[SYSTEMSE]
OK=.\system\se\ok.ogg
CANCEL=.\system\se\cancel.ogg
FOCUS=.\system\se\focus.ogg
MOUSEOVER=.\system\se\mouseover.ogg
ERROR=.\system\se\error.ogg
CHECK=.\system\se\check.ogg
PAGE=.\system\se\page.ogg
START=.\system\se\start.ogg

[SOUNDDEFAULTVOLUME]
BGM=45
Voice=90
SE=70
SystemSE=40
Movie=80
Env=80

; eof
