[SETUP]
CompanyName=3rdEye
GameTitle=ソーサリージョーカーズ
GameClass=椎名里緒 v2.50
GameDir=ソーサリージョーカーズ
GameExe=SJS.EXE
UninstExe=UNINST.EXE
SetupBMP=SETUP.BMP
InstallSelects=1
DefaultSelect=0
InstallTitle0=『ソーサリージョーカーズ』インストール
InstallFiles0=SJS.EXE,RIO.INI,UNINST.EXE,SETUP.INI,README.TXT,OGG.TXT,SJS_S.WAR,SJS_D.WAR,SJS_T.WAR,SJS_M.WAR,SJS_E1.WAR,SJS_E2.WAR,SJS_G1.WAR,SJS_G2.WAR,SJS_G3.WAR,SJS_G4.WAR,SJS_V.WAR,SJS_D2.WAR,SJS_U1.WAR,mv
Shortcuts=4
Shortcut0=SJS.EXE,「ソーサリージョーカーズ」  実行,,ソーサリージョーカーズ
Shortcut1=UNINST.EXE,「ソーサリージョーカーズ」　削除
Shortcut2=README.TXT,初めにお読み下さい
Shortcut3=http://3rdeye.jp/,『3rdEye』ウェブサイト
ExecApp=Explorer.exe,README.TXT
UseCompanyNameForShortcutGroup=1
ChooseSaveDataFolder=1
;1.02
