[GLOBAL]
#MODE1为脚本提取（供无法拆包时使用），MODE2为免封包注入脚本（翻译后的txt放入trans文件夹下）。
MODE=2
#2.48：TYPE=1
#2.49\2.50：TYPE=2
TYPE=1
#为1时启用win10兼容性补丁，需要将win10_patch.dll放入补丁中
WIN10PATCH=1
#调试用
DEBUG=0
[FONT]
FONTNAME=Simsun
[LOADER]
#仅在使用DLLLOADER时需要以下配置
#TARGET输入游戏主程序名
TARGET=PURELOVE.EXE
DLL=SBRioshiina.dll
[STARTMESSAGE]
MODELTYPE=Deepseek-R1