[GLOBAL]
DEBUG=0
CHANGEFONTMODE=3
LOADDLL=shakinshimaFD.dll
CHANGEWINDOW=1
LE=1
[FONT]
PRINTINFO=1
ConditCHANGEFONT=0
CHANGEFONT=1
CHANGECHARSET=0
FONTNAME=Microsoft YaHei UI
FONTFILENAME=0
HeightScaleFactor=100
WidthScaleFactor=100
cWeight=600
rotate=0
[TEXTPROCESS]
#1为提取，2为替换
MODE=1