[release]
; リリース版で最初に実行されるDLLとエントリーを指定します
scenario=sc00.dll
entry=start

[setting]
USER_FOLDER=user\
CLASS=NAO2
TITLE=NaturalAnotherOne 2nd -Belladonna- Deepseek 机翻 by ALyCE/jyxjyx1234
W_VIEW=800
H_VIEW=600
EUDC=retouch.tte
WINCNF=1
N_REG=2048
N_STRREG=256
N_SYSREG=6400
VOICE=1
CHARACTERS=30
N_USAVE=225
N_ASAVE=25
N_QSAVE=3
N_MESSAGE=45000
N_CG=4000
N_SCENE=400
N_SOUND=100
N_LOCREG=100
[option]
recmax=0
WIDE_VOICE=0
record=0

[copyright]
TITLE=NaturalAnotherOne 2nd -Belladonna- Deepseek 机翻 by ALyCE/jyxjyx1234
VERSION=1.1.0
URL=http://www.dreamsoft.jp/nao2nd/index_nao2.html
COPYRIGHT=Copyright(C)2005, Dreamsoft inc. ALL rights reserved.
