[GLOBAL]
DEBUG=0
LE=1
LOADDLL=jyxjyx1234.dll
[FONT]
#模式
A=1
IA=1
#字体名
FONTNAME=Simsun
HEIGHTSCALEFACTOR=100
WIDTHSCALEFACTOR=100
WEIGHT=1000
CHARSET=128
[WINDOW]
ENABLE=0
ORI=交換条件
NEW=
CHECKORI=1
[TEXTREPLACE]
MODE=2
[STARTMESSAGE]
MODELTYPE=Deepseek-R1