from gen_transdict_LIB import *

a = transdict()

#a.addname(jp_name=[],chs_name=[],sex="",role="",other="",reverse=False)

a.addname(jp_name=["プリム＝リナ＝オクレイン"],chs_name=["普莉姆＝莉娜＝奥克雷恩"],sex="girl",role="Twin sister of ライム",other="",reverse=True)
a.addname(jp_name=["ライム＝ルナ＝オクレイン"],chs_name=["莱姆＝露娜＝奥克雷恩"],sex="girl",role="Twin sister of プリム",other="",reverse=True)
a.addname(jp_name=["マリアフィア＝シフォネーゼ"],chs_name=["玛丽亚菲娅＝西波内斯"],sex="girl",role="",other="",reverse=True)
a.addname(jp_name=["ミンティア＝ミミット＝ミディム"],chs_name=["明蒂亚＝米米特＝米迪姆"],sex="girl",role="",other="",reverse=True)
a.addname(jp_name=["チャイム＝ミルフォークス"],chs_name=["查伊姆＝米尔福克斯"],sex="girl",role="younger sister of セラフィナ",other="",reverse=True)
a.addname(jp_name=["六桜 日奈々"],chs_name=["六樱 日奈奈"],sex="girl",role="younger sister of 琥珀",other="",reverse=False)
a.addname(jp_name=["セラフィナ＝ミルフォークス"],chs_name=["塞拉菲娜＝米尔福克斯"],sex="girl",role="elder sister of チャイム",other="",reverse=True)
a.addname(jp_name=["リカルド＝ガディオン"],chs_name=["里卡多＝加迪翁"],sex="man",role="teacher",other="",reverse=True)
a.addname(jp_name=["アルフレッド＝セバスチャン"],chs_name=["阿尔弗雷德＝塞巴斯蒂安"],sex="man",role="Butler",other="",reverse=True)
a.addname(jp_name=["六桜 琥珀"],chs_name=["六樱 琥珀"],sex="boy",role="elder brother of 日奈々",other="",reverse=True)
a.addname(jp_name=["エンリコ＝フルラネット"],chs_name=["恩里科＝弗拉内托"],sex="man",role="teacher",other="",reverse=True)
a.addname(jp_name=["ルルノア＝ロロ＝トラエッタ"],chs_name=["露露诺亚＝洛洛＝特拉埃塔"],sex="woman",role="teacher",other="",reverse=True)
a.addname(jp_name=["ジャコモ＝デリ＝シジズモンド"],chs_name=["贾科莫＝德里＝西斯蒙德"],sex="man",role="",other="",reverse=True)
a.addname(jp_name=["アニタ＝ノーノ"],chs_name=["安妮塔＝诺诺"],sex="girl",role="",other="",reverse=True)
a.addname(jp_name=["タルンカッペ＝ソロ"],chs_name=["塔伦卡佩＝索罗"],sex="",role="teacher",other="",reverse=True)
a.addname(jp_name=["シャロン＝エルフィーナ"],chs_name=["莎朗＝埃尔菲娜"],sex="girl",role="",other="",reverse=True)
a.addname(jp_name=["ユキ＝クランド"],chs_name=["雪＝库尔兰"],sex="girl",role="",other="",reverse=True)
a.addname(jp_name=["ネモ＝ルイージャ"],chs_name=["尼莫＝卢拉"],sex="boy",role="",other="",reverse=True)
a.addname(jp_name=["ロベルト＝エンツォ"],chs_name=["罗伯特＝恩佐"],sex="",role="",other="",reverse=True)
a.addname(jp_name=["キリカ＝フェネシュ"],chs_name=["基里卡＝费内斯"],sex="gilr",role="teacher",other="",reverse=True)
a.addname(jp_name=["ファテシア＝セインテリア＝ヴァンチェスタ"],chs_name=["法特西亚＝塞恩特里亚＝范切斯塔"],sex="girl",role="",other="",reverse=True)
a.addname(jp_name=["ブラネリー＝トロア＝カルシモンド"],chs_name=["布拉内利＝特洛亚＝卡尔西蒙德"],sex="man",role="teacher",other="",reverse=True)
a.addname(jp_name=["ヴァンチェスタ"],chs_name=["范切斯特"],sex="",role="",other="",reverse=False)

a.gen_dict()
#a.savetxt("primary_dict.txt")
a.savejson("primary_dict.json")