[GLOBAL]
DEBUG=0
LE=1
[FONT]
#模式
A=1
IA=1
#字体名
FONTNAME=黑体
HEIGHTSCALEFACTOR=100
WIDTHSCALEFACTOR=100
WEIGHT=900
CHARSET=134
[WINDOW]
ENABLE=1
ORI=
NEW=
CHECKORI=0
[TEXTREPLACE]
MODE=1
[STARTMESSAGE]
MODELTYPE=Deepseek-R1