[GLOBAL]
DEBUG=0
LE=1
[FONT]
A=1
IA=1
W=1
IW=0
#字体名
FONTNAME=ALyCE_Humming
#字体大小调节，100为原大小
HEIGHTSCALEFACTOR=100
WIDTHSCALEFACTOR=100
#调节粗细
WEIGHT=600
[WINDOW]
ENABLE=1
CHECKORI=0
[TEXTREPLACE]
MODE=2
[STARTMESSAGE]
MODELTYPE=Deepseek-R1