[椎名里緒 v2.50]
Reg=software\3rdEye\ソーサリージョーカーズ
WindowWidth=1920
WindowHeight=1080
Scn=start.scn
Arc=SJS_S.WAR
Background=1
Joypad=0
DirectSoundHard=0
DirectSoundPrimaryBuffer=1
SynthiaPCMPriority=1
SynthiaPCMBuffer=4
SynthiaPCMNotify=4
MPEG1Filter=0
MovieMode=0
FullScreen=0
WideMode=2
FreeWindow=1
WindowSizeMenu=0
;1.02
SMSize=0
MMOut=0
