// 環境情報用変数
global.ENV_Maker     = "ユニゾンシフト";
global.ENV_MakerURL  = "http://www.softpal.co.jp/unisonshift/";
global.ENV_GameName  = "おたマ！～おたく仲間はちっこいマニア～";
global.ENV_GameURL   = "http://www.softpal.co.jp/accent/project/project27/";
global.ENV_GameId    = "{48850578-4F14-43B2-A08E-2AE17254A9F7}";
global.ENV_ReadmeFile= "readme.txt";
global.ENV_ReadmeName= "お読みください";
global.ENV_IconFile  = "setup/game.ico";
global.ENV_PKeyName  = "";
// ※このファイルは直接編集しないでください
// （元となる MakeConfig.txt を編集して MakeMenuから直makeの「gameconfig」で更新）
