// HistoryLayer.tjs - メッセージ履歴レイヤ
// Copyright (C)2001-2006, W.Dee and contributors  改変・配布は自由です

/**
 * ダイアログベースのヒストリレイヤ
 */
class MyHistoryLayer extends DialogLayer
{
	// 互換のためにあるが機能しない項目
	var everypage, verticalView, maxPages;


	var actionIndent = 16;
	var actionOffset = 0;
	var nameIndent  = 0;

	var antialiased  = true;  // アンチエイリアス文字描画を行うか
	var verticalView = false; // 縦書きかどうか
	var autoReturn   = true;  // 自動的に改行するかどうか
	var maxLines     = 2000;  // 最大保持行数

	var data       = []; // 行データ ( リングバッファ )
	var lineStart  = []; // 行表示開始位置 ( リングバッファ )
	var actionInfo = []; // 履歴クリック情報 ( リングバッファ )

	var dataStart = 0; // データの開始位置
	var dataLines = 0; // データ中に含まれる行数 < maxLines -1
	var dataPos   = 0; // データ書き込み位置

	// マージン設定は DialogLayer にはない
	var marginL = 12;
	var marginR = 12;
	var marginT = 12;
	var marginB = 12;

	var fontName   = "ＭＳ ゴシック";
	var fontBold   = true;
	var fontHeight = 40;
	var lineHeight = 26;
	var relinePos_org = 0; // 改行位置
	var limitPos_org  = 0; // 画面の端っこ位置
	var relinePos     = 0; // 改行位置
	var limitPos      = 0; // 画面の端っこ位置
	var indentPos     = 0; // インデント位置
	var indentOffset  = 0; // インデント位置補正用
//	var repageLine    = 0; // 改ページ行数

	var fadeTime      = 200; // フェード表示・消去時間

	var historyColor     = 0xffffff; // 履歴文字色
	var historyOverColor = 0xfd9618; // 履歴オーバー色

	var stopVoiceAtOpen  = false; // 開くときに全音声を止める
	var stopVoiceAtClose = -1;  // 閉じるときに全音声を止める(<0:アクションを実行したときに止める, 0:止めない, >0:常に止める)
	var stopVoiceAtCloseOnThisSession;

	var relineAfterName  = false; // 名前の表示の後に改行を入れるか
	var doubleLineSpace  = true;  // ページの行間を２行分にするか

	var scrollOffset; // スムーズスクロール用の現在の１ライン未満（0～lineHeight-1）の値
	var lastDispStart; // textLayerが現在表示中のdispStart位置（スライダーのスクロールで無駄な画像更新を防ぐため）

	var _dispStart = 0;
	property dispStartMax  { getter { return dataLines - dispLines; } }
	property dispStart {
		getter { return _dispStart; }
		setter(v) {
			var max = dispStartMax;
			v = max if (v > max);
			_dispStart = (v >= 0) ? v : 0;
		}
	}
	var dispLines = 0;

	var currentLine = "";
	var _currentText = ""; // セーブデータ参照用テキスト
	property currentText { getter { return _currentText.replace(/\n/g, ""); } setter(v) { _currentText = v; dm("!"); } }
	var currentName = "";

	var currentAction    = void;
	var currentActionExp = void;
	var currentActionID  = 1;

	var lastHighlightedActionID = 0;

	var lastWheelTick; // 最後にホイールを操作した tick count

	var storeState = false; // 状態を栞に保存するか

	//	禁則文字
	var wwFollowing = "%),:;]}｡｣ﾞﾟ。，、．：；゛゜ヽヾゝ"
                "ゞ々’”）〕］｝〉》」』】°′″℃￠％‰"; // 行頭禁則文字
	var wwFollowingWeak="!.?､･ｧｨｩｪｫｬｭｮｯｰ・？！ーぁぃぅぇぉっゃゅょゎァィ"
                "ゥェォッャュョヮヵヶ"; // 行頭(弱)禁則文字
	var wwLeading="\\$([{｢‘“（〔［｛〈《「『【￥＄￡"; // 行末禁則文字

	wwFollowing += wwFollowingWeak;


	var textLayer;
	var baseLayer;
	var uiStorage = "";
	var uiLoaded  = false;
	var bgOpacity = 128;
	var bgColor   = 0;
	var bgLayerType = ltTransparent;

	// 機能ボタンの UIパーツ名デフォルト
	var endPageName  = "end";
	var topPageName  = "top";
	var prevPageName = "pageup";
	var nextPageName = "pagedown";
	var prevLineName = "up";
	var nextLineName = "down";
	var closeName    = "close";
	var sliderName   = "slider";
	var actionName   = "action";
	var baseName     = "base";

	// 効果音
	var opense,  opensebuf;
	var closese, closesebuf;

	function MyHistoryLayer(win, par) {
		super.DialogLayer(win, par, "履歴レイヤ");
		textLayer = new global.KAGLayer(win, this);
		textLayer.name = "TextLayer";
		textLayer.hitThreshold = 256; // イベントはすべて下のレイヤに流す

		(HistoryLayer_config incontextof this)(); // configuration
		(HistoryLayer_config_override incontextof this)()
			if typeof global.HistoryLayer_config_override != "undefined";

		fontUpdate();

		cursor = window.cursorDefault;
		clear();
	}

	function finalize() {
		super.finalize(...);
	}

	// ラッパ
	property font { getter { return textLayer.font; } }
	function drawText()    { return textLayer.drawText(...); }


	function fontUpdate(redraw = false) {
		font.face = (fontName != "") ? fontName : window.chDefaultFace;
		font.height = fontHeight;
		font.bold = fontBold;
		font.angle = 0;
		updatePage() if (redraw && enabled);
	}

	// 内容のクリア
	function clear() {
		lineStart  = [];
		actionInfo = [];
		dataStart  = 0;
		dataLines  = 0;
		dataPos    = 0;

		data       = [];
		lineStart  = [];
		actionInfo = [];

		currentLine = "";
		_currentText = "";

		currentAction    = void;
		currentActionExp = void;
		currentActionID  = 1;

		lastHighlightedActionID = 0;

		calcRelinePos();

		_ctclear = true;
		_stored  = false;
	}

	function save() {
		// 履歴の栞への保存のコードは ゆん氏からいただきました。
		// この場を借りてお礼申し上げます。
		if(!storeState) return void;
		var dic = %[];

		(dic.lineStart  = []).assignStruct(lineStart);
		(dic.actionInfo = []).assignStruct(actionInfo);
		(dic.data       = []).assignStruct(data);

		dic.dataStart				= dataStart;
		dic.dataPos					= dataPos;
		dic.dataLines				= dataLines;
		dic.currentLine				= currentLine;
		dic.currentText				= _currentText;
		dic.currentAction			= currentAction;
		dic.currentActionExp		= currentActionExp;
		dic.currentActionID			= currentActionID;
		dic.lastHighlightedActionID	= lastHighlightedActionID;
		return dic;
	}

	function load(dic) {
		if(!storeState) return;
		if(dic === void) return;

		lineStart.assignStruct( dic.lineStart);
		actionInfo.assignStruct(dic.actionInfo);
		data.assignStruct(      dic.data);

		dataStart				= dic.dataStart;
		dataPos					= dic.dataPos;
		dataLines				= dic.dataLines;
		currentLine				= dic.currentLine;
		_currentText			= dic.currentText;
		currentAction			= dic.currentAction;
		currentActionExp		= dic.currentActionExp;
		currentActionID			= dic.currentActionID;
		lastHighlightedActionID	= dic.lastHighlightedActionID;
		calcRelinePos();
	}

	function calcRelinePos() {
		relinePos = relinePos_org = width - marginL - marginR;
		//	改ページの基準となる行数を計算
		limitPos = limitPos_org = width - marginL;
//		repageLine	= (height - marginT - marginB) \ lineHeight;
	}

	function setOptions(elm) {
		super.setOptions(...);

		// マージン上書き
		marginL = +elm.marginl if elm.marginl !== void;
		marginT = +elm.margint if elm.margint !== void;
		marginR = +elm.marginr if elm.marginr !== void;
		marginB = +elm.marginb if elm.marginb !== void;

		// フォント関連
		fontName     =  elm.fontname     if elm.fontname     !== void;
		fontBold     = +elm.fontbold     if elm.fontbold     !== void;
		fontHeight   = +elm.fontheight   if elm.fontheight   !== void;
		lineHeight   = +elm.lineheight   if elm.lineheight   !== void;
		fontUpdate();

		// その他
//		verticalView = +elm.verticalview if elm.verticalview !== void;
//		everypage    = +elm.everypage    if elm.everypage    !== void;
		autoReturn   = +elm.autoreturn   if elm.autoreturn   !== void;

		maxLines     = +elm.maxlines     if elm.maxlines     !== void;
		storeState   = +elm.storestate   if elm.storestate   !== void;
		actionIndent = +elm.actionindent if elm.actionindent !== void;
		nameIndent   = +elm.nameindent   if elm.nameindent   !== void;
		relineAfterName = +elm.relineaftername if elm.relineaftername !== void;
		doubleLineSpace = +elm.doublelinespace if elm.doublelinespace !== void;

		fadeTime     = +elm.fadetime     if elm.fadetime     !== void;

		// UI関連
		uiLoaded = false if (elm.storage != "" && uiStorage != elm.storage);
		uiStorage    =  elm.storage      if elm.storage      !=  "";
		bgColor      =  elm.bgcolor      if elm.bgcolor      !== void;
		bgOpacity    =  elm.bgopacity    if elm.bgopacity    !== void;
		bgLayerType  =  Scripts.eval(elm.type) if elm.type   !== void;

		// パーツ名
		topPageName  =  elm.toppage      if elm.toppage      !== void;
		endPageName  =  elm.endpage      if elm.endpage      !== void;
		prevPageName =  elm.prevpage     if elm.prevpage     !== void;
		nextPageName =  elm.nextpage     if elm.nextpage     !== void;
		prevLineName =  elm.prevline     if elm.prevline     !== void;
		nextLineName =  elm.nextline     if elm.nextline     !== void;
		closeName    =  elm.close        if elm.close        !== void;
		sliderName   =  elm.slider       if elm.slider       !== void;
		actionName   =  elm.action       if elm.action       !== void;
		baseName     =  elm.base         if elm.base         !== void;

		// 効果音
		opense       =  elm.opense       if elm.opense       !== void;
		closese      =  elm.closese      if elm.closese      !== void;
		opensebuf    = (elm.opensebuf  !== void) ? +elm.opensebuf  : kag.numSEBuffers - 1;
		closesebuf   = (elm.closesebuf !== void) ? +elm.closesebuf : kag.numSEBuffers - 1;

		makeButtons() if (elm.uiload);
	}
	// alias
	function setPosition() { super.setPosition(...); setOptions(...); }
	function makeButtons() {
		if (uiLoaded) return;
		var elm = %[ bgcolor:bgColor, bgopacity:bgOpacity,
					 color:frameColor, opacity:frameOpacity,
					 storage:uiStorage, visible:false,
					 marginl: marginL, marginr: marginR,
					 margint: marginT, marginb: marginB
					 ];

		var vis = visible;
		if (uiStorage != "") uiload(elm);
		else setPosition(elm);
		visible = vis;

		with (textLayer) {
			.setImagePos(0, 0);
			.setImageSize(width, height);
			.setPos(0, 0, width, height);
			.visible = true;
		}
		if (baseName != "") {
			baseLayer = names[baseName];
			if (baseLayer !== void) with (baseLayer) {
				.type = bgLayerType;
				.setImageSize(.width, .height);
			}
		} else baseLayer = void;
		if (actionName != "") {
			var mark = names[actionName];
			if (mark !== void) with (mark) {
				.visible = false;
				actionOffset = (actionIndent < 0) ? (-actionIndent + .width) : -(actionIndent + .width);
			}
		}
		if (sliderName != "") {
			setButtonProp(sliderName, "focusable", false); // フォーカスを受け取らないように
			var slider = names[sliderName];
			if (slider !== void) with(slider) {
				.onChange = this.onSliderChange;
			}
		}

		calcRelinePos();
		uiLoaded = true;
	}

	property lastLine {
		getter       { return data[dataPos]; }
		setter(line) { data[dataPos] = line; }
	}
	property lastLineStart {
		getter       { return lineStart[dataPos]; }
		setter(ls)   { lineStart[dataPos] = ls; }
	}
	property lastAction {
		getter       { return actionInfo[dataPos]; }
		setter(n)    { actionInfo[dataPos] = n;    }
	}

	// n 番目の行のデータの位置を得る
	function getLineOffset(n) {
		n += dataStart;
		n -= maxLines if n >= maxLines;
		return n;
	}
	function getLine(n)       { return data[      getLineOffset(n)]; }
	function getLineStart(n)  { return lineStart[ getLineOffset(n)]; }
	function getActionInfo(n) { return actionInfo[getLineOffset(n)]; }

	function endAction() {
		if (currentAction === void) return;
		// 現在のアクションがすでにある場合
		var ca = currentAction;
		var last = ca[ca.count - 1];
		last.end = font.getTextWidth(currentLine);

		// アクションマーク分
		var mark = names[actionName];
		if (mark !== void && ca[0].first) {
		}
	}

	function setLastAction(first) {
		currentAction = [] if (currentAction == void);
		var last    = currentAction[currentAction.count] = %[];
		currentActionID++ if first;
		with (last) {
			.start  = font.getTextWidth(currentLine);
			.action = currentActionExp;
			.id     = currentActionID;
			.first  = first;
		}
	}

	function setNewAction(action) {
		// アクションを新規に設定する
		if (action == "" || action === void) return;
		endAction();
		currentActionExp = action;
		setLastAction(true);
	}

	function continueAction() {
		setLastAction(false) if (currentActionExp !== void);
	}

	function clearAction() {
		endAction();
		currentActionExp = void;
	}

	var _stored = false, _ctclear = true;
	function internalStore(ch, clr = false) {
		_stored = true;
		_ctclear = clr;
		if (!autoReturn) {
			// 自動改行を行わない場合
			currentLine += ch;
		} else {
			// 自動改行を行う場合
			var len;
			if((len = font.getTextWidth(currentLine += ch)) >= relinePos)
			{
				var curlen = currentLine.length;
				var lastch = curlen >= 2 ? currentLine[curlen - 2] : '';

				if(((lastch=='' || wwLeading.indexOf(lastch)==-1) &&
					wwFollowing.indexOf(ch)==-1) ||
					(lastch!='' && wwFollowingWeak.indexOf(lastch)!=-1 &&
						wwFollowingWeak.indexOf(ch)!=-1) || len > limitPos)
				{
					// 最後に描画したのが行末禁則文字でない場合
					// しかもこれから描画するのが行頭禁則文字でない場合
					// または弱禁則文字が連続していない場合
					// はたまたこれから描画するのが強禁則文字ではなくて、
					// 確実に 右端を越える場合
					// ( この場合は余白は考えない )
					//			  追加した文字を取り除く
					currentLine = currentLine.substring(0, currentLine.length - ch.length);
					reline(false);
					currentLine = ch;
				}
			}
		}
	}
	function store(ch) {
		if (_ctclear) _currentText = "";
		_currentText += ch;
		internalStore(ch, false);
	}
	function storeNameFilter(name) {
//		var spc = (name.length == 1 ? "　" : name.length == 2 ? " " : "";
//		return @"【${spc}${name}${spc}}】";
		return name;
	}
	function storeName(name) {
		currentName = name;
		if (name == "" || ((string)name).trim() == "") return;
		name = storeNameFilter(name);
		var indent = getNameIndent(name);
		indentOffset  = -indent;
		lastLineStart -= indent;
		relinePos     += indent;
		internalStore(name, true);
		reline(false) if (relineAfterName);
	}
	function getNameIndent(text) { return nameIndent; }

	//	改ページ
	function repage(force = false) {
		if (force) _currentText = "";
		else _ctclear = true;
	}

	// 改行
	function reline(dl = true) {
		reline(false) if (dl && !_stored && doubleLineSpace);
		_stored = false;
//		_ctclear = true if dl;
		_currentText += "\n" if (dl && _currentText != "");

		endAction();
		lastLine = currentLine;
		lastAction = currentAction;

		// 自動改行オフの場合ははみ出ていないかチェック
		if (!autoReturn && currentLine != "") {
			var x = marginL + lastLineStart + font.getTextWidth(currentLine);
			if (x > width - marginR) {
				var msg = "バックログがマージン領域から溢れている可能性があります："+currentLine;
				if (typeof window.errorCmd == "Object")
					/**/   window.errorCmd(msg);
				else dm(msg);
			}
		}

		dataPos++;
		if(dataPos >= maxLines) dataPos=0;
		data[dataPos] = void;
		lineStart[dataPos] = indentPos;
		actionInfo[dataPos] = void;

		limitPos = limitPos_org - indentPos;
		relinePos = relinePos_org - indentPos;
		indentOffset = 0;
		if (dataPos ==   dataStart) dataStart++;
		if (dataStart >= maxLines)  dataStart = 0;
		if (dataLines <  maxLines)  dataLines++;

		currentAction = void;
		currentLine = '';
		continueAction();
	}
	function autoReline() {
		if (!autoReturn) reline();
	}

	function preIndent() {
		var w = font.getTextWidth("　");
		lastLineStart -= w;
		indentOffset -= w;
	}

	function beginIndent() {
		// 現在位置にインデントを設定
		indentPos = font.getTextWidth(currentLine) + indentOffset;
	}

	function endIndent() {
		// インデントを解除
		indentPos = 0;
	}

	function clearBack(n) {
		with (textLayer) {
			var isAll = (n === void);
			.face = dfAlpha;
			.fillRect(/*x*/0,           /*y*/(isAll ? 0            : (n * lineHeight + marginT)),
					  /*w*/.imageWidth, /*h*/(isAll ? .imageHeight : lineHeight), /*col*/ 0x00000000);
		}
	}

	function dispInit() {
		setClickHook(true);
		window.hideMessageLayerByUser();

		// 全部再描画と初期設定
		makeButtons(); // ボタンを作成

		lastLine = currentLine;
		endAction();
		lastAction = currentAction;

		antialiased = window.chDefaultAntialiased;

		dispLines = (height - marginT - marginB) \ lineHeight;
		dispStart = canScroll ? dispStartMax : 0;

		lastDispStart = -1;
		scrollOffset = 0;

		// textLayerのクリップのための処理（互換優先のため，かなり無駄な領域ががあります）
		with (textLayer) {
			.imageHeight = height + lineHeight;
			.height = dispLines * lineHeight;
			.top = marginT;
			.imageTop = -marginT;
		}

		// スライダ上限下限
		if (canScroll) {
			setButtonProp(sliderName, "min", 0);
			setButtonProp(sliderName, "max", dispStart * lineHeight);
		}
		updatePage();

		enabled = true;
		if (baseLayer !== void) with (baseLayer) {
			.parent   = this.parent;
			.absolute = this.absolute-1;
//			.visible = true;
		}
		opacity = 255;
		visible = true;

		setMode();
		focus();
		lastWheelTick = 0;
		cursor = window.cursorDefault;

		stopAllVoice() if (stopVoiceAtOpen);
		stopVoiceAtCloseOnThisSession = (stopVoiceAtClose > 0);
		kag.se[opensebuf].play(%[storage:opense]) if (opense !== void);

		if (fadeTime > 0) {
			startByKey = false;
			enabled = false;
			window.stopAction (this);
			window.beginAction(this, %[ opacity:%[ handler:MoveAction, start:(opacity=0), value:255, time:fadeTime ] ],
							   function { enabled = true; focus(); } incontextof this, true);
		}
	}

	function dispUninit() {
		if (!visible) return;

		// window から呼ばれる
		removeMode();
		enabled = false;

		stopAllVoice() if (stopVoiceAtCloseOnThisSession);
		kag.se[closesebuf].play(%[storage:closese]) if (closese !== void);

		if (fadeTime > 0) {
			window.stopAction (this);
			window.beginAction(this, %[ opacity:%[ handler:MoveAction, start:255, value:0, time:fadeTime ] ],
							   dispUninit2, true);
		} else dispUninit2();
	}
	function dispUninit2() {
		if (!isvalid this) return;
		setClickHook(false);
		visible = false;
//		baseLayer.visible = false if (baseLayer !== void);
		window.showMessageLayerByUser();
	}

	property visible {
		setter(v) {     super.visible = v; if (baseLayer !== void) baseLayer.visible = v; }
		getter { return super.visible; }
	}
	property opacity {
		setter(v) {     super.opacity = v; if (baseLayer !== void) baseLayer.opacity = v; }
		getter { return super.opacity; }
	}


	function stopAllVoice() {
		if (typeof global.world_object != "undefined" &&
			typeof global.world_object.env != "undefined" &&
			typeof global.world_object.env.stopAllVoice != "undefined")
			/*  */ global.world_object.env.stopAllVoice();
	}

	function drawActionMark(x, y, n, over=false) {
		var ai = getActionInfo(n + dispStart);
		var mark = names[actionName];
		// アクションが無い場合表示しない
		if (ai === void || !ai[0].first || mark === void) return;
		with (mark) {
			x += ai[0].end - .width if (actionOffset >= 0);
			textLayer.operateRect(x + actionOffset, y,
								  mark, (over ? .width*2 : 0), 0, .width, .height);
		}
	}
	function drawLineTextAndMark(x, y, n, over, col, line) {
		drawText(x, y, line, col, 255, antialiased);
		drawActionMark(x, y, n, over);
	}
	function drawLine(n, over=false, *) {
		// 表示行 n を描画する
		var line      = getLine(     n + dispStart);
		var linestart = getLineStart(n + dispStart);

		var x = marginL + linestart;
		var y = n*lineHeight + marginT;
		var col = over ? historyOverColor : historyColor;
		drawLineTextAndMark(x, y, n, over, col, line, *);
	}

	function drawPage() { dm("no implement: MyHistoryLayer.drawPage()"); }

	function updatePage(move = 0) {
		if (move !== 0) {
			var to = (dispStart + move);
			dispStart = to;
			if (to != dispStart) {
				scrollOffset = 0; // 端に到達
				textLayer.imageTop = -marginT; // [XXX]
			}
		}
		//dm("updatePage", dispStart, scrollOffset);
		clearActionHighlights(false);
		clearBack();
		for(var i = 0, cnt = dispLines+1; i < cnt; i++) drawLine(i);
		updateButtonState();
	}

	function getLineNumFromPos(y) {
		var line = (y - marginT + scrollOffset) \ lineHeight;
		var maxl = (dataLines < dispLines) ? dataLines : (dispLines+(scrollOffset?1:0));
		if (line < 0 || line >= maxl) return void; // はみ出ている
		return line;
	}
	function getActionInfoFromPos(x, y) {
		// x,y 位置のアクション ID を得る
		if (y < marginT || y >= marginT + dispLines * lineHeight) return;
		var line = getLineNumFromPos(y);
		if (line === void) return;
		var pos = line + dispStart;
		var ai = getActionInfo(pos);
		var ls = getLineStart( pos);

		if(ai === void) return void; // 情報がない
		var p = x - (marginL + ls);
		for(var i = ai.count - 1; i >= 0; i--) with (ai[i]) {
			if (.end === void) continue; // 行が完結していない
			var s = .start, e = .end;
			// アクションマーク分も含める
			if (.first && actionOffset != 0) {
				if (actionOffset < 0) s += actionOffset;
				else                  e += actionOffset;
			}
			if (s < p && p <= e) return ai[i];
		}
		return void;
	}

	function getActionLines(id) {
		var ret = [];
		if (id == 0) return ret;
		var max = (dataLines <= dispLines) ? dataLines : (dispLines+(scrollOffset?1:0));
		for(var i = 0; i < max; i++) {
			var ai = getActionInfo(i + dispStart);
			if (ai === void) continue;
			for(var j = ai.count - 1; j >= 0; j--) {
				var info = ai[j];
				ret.add(i) if (info.end !== void && info.id == id);
			}
		}
		return ret;
	}

	function updateActionLines(id, *) {
		var lines = getActionLines(id);
		for (var i = 0; i < lines.count; i++) clearBack(lines[i]);
		for (var i = 0; i < lines.count; i++) drawLine( lines[i], *);
	}

	// 画面上にある ID で示された ID をすべて ハイライトする
	function highlightAction(id) {
		lastHighlightedActionID = id;
		updateActionLines(id, true);
	}

	// 画面上にある lastHighlightedActionID で示されたハイライト表示をすべて消す
	function clearActionHighlights(update = true) {
		if (lastHighlightedActionID == 0) return;
		updateActionLines(lastHighlightedActionID) if update;
		lastHighlightedActionID = 0;
		cursor = window.cursorDefault;
	}

	function setButtonProp(name, prop, value) {
		var target = names[name];
		target[prop] = value if (target !== void);
	}

	var nowUpdating;
	function updateButtonState() {
		nowUpdating = true;
		var up = canScrollUp, down = canScrollDown;
		setButtonProp(prevPageName, "enabled", up);
		setButtonProp(prevLineName, "enabled", up);
		setButtonProp(topPageName,  "enabled", up);
		setButtonProp(endPageName,  "enabled", down);
		setButtonProp(nextPageName, "enabled", down);
		setButtonProp(nextLineName, "enabled", down);

		setButtonProp(sliderName,   "enabled", canScroll);
		setButtonProp(sliderName,   "position", dispStart * lineHeight + scrollOffset);
		nowUpdating = false;
	}

	property canScroll     { getter { return dispStartMax > 0; } }
	property canScrollUp   { getter { return canScroll && (dispStart > 0 || scrollOffset); } }
	property canScrollDown { getter { return canScroll && (dispStart < dispStartMax || scrollOffset); } }

	function scrollDown()  { if (canScrollDown) updatePage( 1); }
	function scrollUp()    { if (canScrollUp)   updatePage(-1); }
	function nextPage()    { if (canScrollDown) updatePage( dispLines); }
	function prevPage()    { if (canScrollUp)   updatePage(-dispLines); }
	function endPage()     { if (canScroll) { dispStart = dispStartMax; scrollOffset = 0; updatePage(); } }
	function topPage()     { if (canScroll) { dispStart = 0;            scrollOffset = 0; updatePage(); } }

	function hide() {
		releaseCapture();
		window.hideHistory();
	}

	function execButton(name) {
		switch (name) {
		case endPageName:  endPage();    break;
		case topPageName:  topPage();    break;
		case prevPageName: prevPage();   break;
		case nextPageName: nextPage();   break;
		case prevLineName: scrollUp();   break;
		case nextLineName: scrollDown(); break;
		case closeName:    hide();       break;
		}
	}
	function onButtonClick(num) {
		super.onButtonClick(num);
		var target = this.links[num].object;
		if (target === void) return;
		execButton(target.name);
	}

	function onSliderChange(pos, drag) { //sender, pos) {
		if(!canScroll || nowUpdating) return;
		scrollOffset = pos % lineHeight;
		dispStart    = pos \ lineHeight;
		textLayer.imageTop = -marginT -scrollOffset;
		if (lastDispStart < 0 || dispStart != lastDispStart) {
			// [TODO] lastDispStartを見て既に表示しているテキストから差分のみの更新にできないか
			lastDispStart = dispStart;
			updatePage();
		}
	}

	// 開く処理 (DialogLayerから呼ばれる)
	function open() {
		// super.open() は呼ばない
	}
	// 閉じる処理 (DialogLayerから呼ばれる)
	function close() {
		hide();
		// super.close() は呼ばない
	}



	function onMouseUp(x, y, button, shift) {
		if (button == mbLeft) {
			var n = getActionInfoFromPos(x,y);
			if (n !== void) {
				Scripts.eval(n.action);
				stopVoiceAtCloseOnThisSession = true if (stopVoiceAtClose < 0);
			}
		} else super.onMouseUp(...);
	}

	function onMouseMove(x, y, shift) {
		var n = getActionInfoFromPos(x,y);
		n = (n === void) ? 0 : n.id;
		if (lastHighlightedActionID != n) {
			clearActionHighlights();
			highlightAction(n);
//			lastHighlightedActionID = n;
			if (n) cursor = window.cursorPointed;
		}
		super.onMouseMove(...);
	}

	function onMouseLeave() {
		clearActionHighlights();
		super.onMouseLeave(...);
	}

	function onKeyPress(key) {
		super.onKeyPress(...);
	}

	var startByKey;
	function onKeyDown(key)
	{
		if (startByKey) {
			startByKey = false;
			return;
		}
		window.hideMouseCursor();

		switch (key) {
		case VK_DOWN:  scrollDown(); break;
		case VK_UP:    scrollUp();   break;

		case VK_LEFT:  
		case VK_PRIOR: prevPage();   break;

		case VK_RIGHT: 
		case VK_NEXT:  nextPage();   break;

		case VK_HOME:  topPage();    break;
		case VK_END:   endPage();    break;

		case VK_ESCAPE:
		case VK_RETURN:
		case VK_SPACE: hide();       break;

		default:
			kag.preProcessKeys(key);
		}
	}

	function windowMouseWheel(shift, delta, x, y)
	{
		// ウィンドウのホイール操作メッセージがここに流される
		var currenttick = System.getTickCount();
		delta = delta \ 120;
		/* くるくる回しているうちにいきなり履歴が閉じたりしないような仕掛け */
		if (delta < 0 && currenttick - lastWheelTick > 150 && !canScrollDown) hide();
		else if (delta < 0 && canScrollDown) while (delta++) scrollDown(); // 手前
		else if (delta > 0 && canScrollUp)   while (delta--) scrollUp();   // 奥
		lastWheelTick = currenttick;
	}
}

global.HistoryLayer = MyHistoryLayer;

// historyopt タグを追加
addKagHandler("historyopt", function(elm) {
	elementSysSE(elm, "history", [ "open", "close" ]);
	with (historyLayer) {
		if (elm.storage != "" && typeof .execDialogHook == "undefined") {
			.execDialogHook = true;
			SystemHook.add("execdialog.start", .makeButtons);
		}
		.setOptions(elm);
	}
	return 0;
}, true);
