/*
検索パスの追加登録方法：
 setupSubFolders([ サブフォルダ名, ... ]);
  サブフォルダ名：data/以下のフォルダ名。サブサブフォルダ以下は"/"で区切る
 */

setupSubFolders([

	"fgimage",
	"fgimage/01-日本橋きらら",
	"fgimage/02-青葉まみ",
	"fgimage/03-大手町もみじ",
	"fgimage/04-大宮いいな",
	"fgimage/05-大洲こより",
	"fgimage/06-天神あめり（ちび）",
	"fgimage/07-天神あめり（正体）",
	"fgimage/08-ＳＰケリー",


	"scenario/",
	"scenario/A",
	"scenario/B",
	"scenario/C",
	"scenario/D",
	"scenario/E",
	"scenario/F",

	"evimage/SD",

	"image/スタッフロール素材",

	"thum/cgmode",
	"thum/scenemode",
	"thum/save",

	"voice/ameri_001",
	"voice/iina_001",
	"voice/kerry_001",
	"voice/kirara_001_ogg",
	"voice/koyori_001",
	"voice/mami_001_ogg",
	"voice/momiji_001",
	"voice/other",


	"sound/w",
	"sound/sysse",


	/* 記述例：
	"scenario/part1"
	"scenario/part2"


	"image/cutin",
	"image/effect/type1",
	"image/effect/type2",

	"voice/chara1",
	"voice/chara2",
	 ここまでコメント */

	

	]);


