[GLOBAL]
DEBUG=0
CHANGECHARSET=0
CHANGEFONT=1
FONTNAME=oshietetfont_sakura
FONTFILENAME=oshietetfont_sakura.ttf
[HOOK]
ORIOFFSET=1346881
RETOFFSET=1346886
CALLOFFSET=309984
[TEXTPROCESS]
ENABLE=1
#1为提取，2为替换
MODE=2
REMOVENAME=0
